include ../Makefile.conf

MODULE_NAME = OpenTLD/src/libopentld/tld
MODULE_COMMENT = OpenTLD/src/libopentld/tld

LINK = g++

CXXFLAGS += 
CFLAGS += 
IFLAGS += 
LFLAGS += 
SUBDIRS += 

SOURCES =  
PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES =  
TARGETS = 
PUBLIC_BINARIES = 

include ../../../../../Makefile.rules
