include ../../../Makefile.conf

MODULE_NAME = OpenTLD/src
MODULE_COMMENT = OpenTLD/src

LINK = g++

CXXFLAGS += 
CFLAGS += 
IFLAGS += 
LFLAGS += 
SUBDIRS += libopentld 3rdparty opentld

SOURCES =  
PUBLIC_INCLUDES = 
PUBLIC_LIBRARIES =  
TARGETS = 
PUBLIC_BINARIES = 

include ../../../Makefile.rules
